name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npx npm@latest i

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npx npm@latest i

      - name: Playground prepare
        run: npm run dev:prepare
        env:
          MUSIC_KIT_DEVELOPER_KEY: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHf0OGUU1tMUbIEk7\nJwrK9JZWohHtOiX6XjaGpYWELmGgCgYIKoZIzj0DAQehRANCAATDdHEJpymreX2W\nZU3cLTinB2t4X9o0ZfJr2Aohrs82zbboW6qBnAqiomHbXozPAxvwi1YwXzALzH28\nYcGkJxnh\n-----END PRIVATE KEY-----"
          MUSIC_KIT_TEAM_ID: "your team id"
          MUSIC_KIT_KEY_ID: "key id"
          MUSIC_KIT_APP_NAME: "app name"
          MUSIC_KIT_APP_BUILD: "app build"

      - name: Test
        run: npm run test
